### ISSUE TITLE
Photos missing 

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#157]
Vixydish reported:

The images I uploaded for today (Sat, 12/8) doesn't show up under the "Week" category.  However, by "Day", they show up.  See screenshots attached.  I'm using Firefox.

By day: https://dl.dropbox.com/u/125982/by_day.jpg
By week: https://dl.dropbox.com/u/125982/by_week.jpg

**Comment by jdaudier** [comment]
Vicky reported at 5:19pm today:

I'm uploading food photos for today (Sunday) and it's showing up under Monday (tomorrow).  When I go edit the date to today, the food photos disappear completely from the by Week option.  Looks like both of the Saturday and Sunday photos aren't showing by the "Week" option.

**Comment by jdaudier** [comment]
Vicky said:

I tried Chrome and IE and both of those browsers, I still can't see the food photos I uploaded for today.  It doesn't show any photos when I view by Day or by Week.  It shows up when I view by month but when I I upload the photos, it would set the date to tomorrow - not sure if it's the same bug or what.

**Comment by jdaudier** [comment]
Can you log in as her and fix this asap?  She using the latest Firefox browser on a PC.

**Comment by loicginoux** [comment]
yes, looking at it now...

**Comment by loicginoux** [comment]
Ok I updated the code. Most of issues you are logging are due to timezone problems. I think I managed to make progress on this bug by changing my computer timezone to PST (your one). I then managed to reproduce the errors you had (which I couldn't before). From there I made the change necessary to have all displayed correctly.
Please try again and let me know if I managed to fix this bug. At least her photos are now similar in week and day view.
Also photos shouldn't jump from one day to another, etc...

**Comment by loicginoux** [comment]
Sorry there is still a bug when updating the asset

**Comment by loicginoux** [comment]
I can now upload and edit a photo fine with Vicky's account. I still have the bug on your account when the upload box get stuck. I continue on your bug.

**Comment by loicginoux** [comment]
Is Vicky's bug solved?
