### ISSUE TITLE
Cannot send in photos using iPhone 5

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#204]
From: andywilfong@hotmail.com
Date: Thu, 3 Jan 2013 09:16:01 -0500

I emailed a picture from my phone, but I got an email this morning that said I have not sent in or uploaded any pictures...I have an iphone 5
Picture was sent from the same email address I have on file with you all.

The email address I sent it to was: pic@foodrubix.mailgun.org
The file size of the picture I sent was 595Kb.  I just sent another email from my phone with the same picture and shrunk the size of the picture to 131Kb to see if that helped.

**Comment by jdaudier** [comment]
Maybe we have issues with Hotmail accounts since Gwen couldn't send from phone and she has a Hotmail email as well.

**Comment by loicginoux** [comment]
This is because his email in database is "Andywilfong@hotmail.com" and when receiving the email the sender is "andywilfong@hotmail.com" so the user is not found.
What I am gonna do is first lowercase manually his email address and then lowercase all email address when registering in the site.

I can try again from now

**Comment by loicginoux** [comment]
I am closing this issue as I think the problem was lowercasing. Please reopen if it didn't fix it
