### ISSUE TITLE
Email response when account not in system is used to send photos

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#207]
Have a way to register a main email address (the current one) but being able to add more address with which you could send photos.

The email could link them to Settings and have them add an additional email and set which one to send the photos from.

I also like this idea if it's easier:
send back an email saying that no account has been found with this email address and that maybe the user signed up with another address, and that he can check what email address is registered by going to his setting page.

Maybe we can link them to the Settings page so they can go there with one click to update the email.

**Comment by loicginoux** [comment]
If the email is wrong this is what you will see in the body of the mail:
Hi,
We are sorry but the email you just sent to upload a photo did not work.
We couldn't find the user account with the email "mywrong@email.com".
You can check what email address is registered by going to your settings page.

Unfortunately I won't be able to put a link to their setting pages because I don't know what user it is...

**Comment by loicginoux** [comment]
this is in testing instance, you can test by sending a email to pic@devfoodrubix.mailgun.org with a wrong email address or by forgetting to attach a photo
