### ISSUE TITLE
email upload enhancement discusion

### ISSUE THREAD

**Issue by loicginoux** [loicginoux/joanne_project#244]
let's see if we can find a way to improve the way we upload photos via email...

**Comment by loicginoux** [comment]
Maybe we could add in the body of the mail a way to add date and description... 
for example having something like:
date: 2012-02-17 10:28 am
description: "this is what I ate this day"

I already thought about that but the problems I can see with this are:
- if date is not formated correctly, it won't work. We need to list all formats of date that will be allowed
- keywords "date: " and "description:" needs to be present to recognize what is what when processing the email, if there is an error with them, it won't be added to the photo.
- if the description is not inside a quotation mark " " I won't be able to detect when the description is finished.
  
  Do you have another idea?
  For me this is a workaround, and an app will easier fit our need but this is another story...

**Comment by jdaudier** [comment]
I'd say to skip the date part since that might be too much for most users.  And this will be fixed once we have a mobile app or mobile web page.

What if we told the user they can put the description in the body of the email by itself, no quotes?  Meaning you would take all the text found in the body of the email.  Is that possible?

**Comment by loicginoux** [comment]
ok good this is really simple to do. I will just add this on the next push. I will let you know here
