### ISSUE TITLE
FB log in

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#26]
A friend of mine tried to log in via FB and said he couldn't.  Might want to check this one out.

**Comment by loicginoux** [comment]
hello,
from what I tested, the thing that can be misleading is that it works this way:
- the user is new on the app, it goes to the register page.
- on the page, all fields are empty.
- it clicks "log in with fb"
- after having accepted all permissions stuff, it redirects you to the register page.
- in the register page you have now the username and email pre filled with your fb details but you need to add the password fields in order to use in the future not only the fb logging method but also the direct method username+password

because there is no message to tell you "we also need your password" this can be confusing as the page reaload and there is almost any change, only the field pre-filled.
do you want to change this behaviour? do you want me to try adding a message when redirected on the register page?

**Comment by jdaudier** [comment]
I tried to log in with another FB account, it seems like if I click on the "log in with FB" button the 2nd time, it doesn't go anywhere.  So at this stage, should we hide the FB button?  http://www.diigo.com/item/image/2yj1s/ehs4

After I chose to log in with FB, I entered my password and clicked "Create Account" button on the left and got to a broken link: http://www.diigo.com/item/image/2yj1s/wx97

**Comment by jdaudier** [comment]
Maybe we can add something like:

Complete your registration

You have been authenticated via Facebook. Please complete your registration below.

**Comment by jdaudier** [comment]
Should we hide the 2nd time the "log in with FB" button shows up since it seems you need to click on the the "create account" button to actually create the account, correct?

**Comment by loicginoux** [comment]
Yes, I will do that as well

**Comment by loicginoux** [comment]
ok I changed the way it works as we said. it's on heroku. Can you test it and close the issue if it's ok.

**Comment by jdaudier** [comment]
Could you delete the account that's using joanne.daudier@splashtop.com and I will try it?  Right now it's logging me in right away.  Thanks!

**Comment by loicginoux** [comment]
You can do it. I show you, I use this page: 
http://quiet-summer-5721.herokuapp.com/users
just destroy the user you want.
This is the easy solution for now but I will need to secure this page later.

**Comment by jdaudier** [comment]
When I click "sign up", I see this page right away even though I didn't click on any sign up with FB button.  Is that right?  http://screencast.com/t/MiKaZIR2QP

**Comment by loicginoux** [comment]
No it's just because you played with it before (a session variable is still there). restart your browser and it should be ok.

**Comment by jdaudier** [comment]
We have someone from Cornell using our app?  Is that your friend?  I wonder if they have uploaded images. rmf34@cornell.edu

**Comment by loicginoux** [comment]
nope

**Comment by jdaudier** [comment]
Nope meaning they didn't upload images?  How about the other users?  

I tried logging in with a new FB account and it worked.  Closed!  Yay!

**Comment by loicginoux** [comment]
Sorry, I don't know anyone who logged in. I would have to dig a bit more in the heroku database to see if they uploaded images. I will do that later if you don't mind.

**Comment by jdaudier** [comment]
Sure - no rush... just curious that's all.
