### ISSUE TITLE
Upload time bug?

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#274]
I noticed that Chrissy has photos for Monday but it's not Monday yet:

http://www.foodrubix.com/chrissy

Right now it's Sun 10:13pm my time.  Chrissy is in Canadian time.

**Comment by loicginoux** [comment]
this is because we decided that we should see photos from other users in their local time they posted it, as this makes more sense when watching at what time people eat, etc...
she has her photos on Monday 12AM so it was already Monday for her and not yet for you. I think this is the reason why.
So more generally, for all people in advance in time from you, you will see their photo as if it was in your future.

**Comment by jdaudier** [comment]
Not a bug since Chrissy said she sent the photos in past midnight.
