### ISSUE TITLE
Change dashboard to homepage

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#30]
Can the dashboard page be moved to the homepage?  Meaning, once you log in, you see your meal photos right away.

And can we change "Dashboard" link to "Following"?  I'll mock up that page.  Basically, once you follow someone, their photo shows up on a list and you can click on the photo to see the other person's meals.

**Comment by jdaudier** [comment]
There's a page that shows everyone:
https://www.dropbox.com/s/j25r3814qg7wf3n/everyone-page.png

From that page, maybe we can add a follow icon to the top right corner of the image (an eye icon) that will let you follow that person.

That person will then show up on your "following" page:
https://www.dropbox.com/s/np09erztnt8dqau/following-page.png

When you click on a person you're following from that page, you see their journal - just like how you would see your journal.

**Comment by loicginoux** [comment]
ok, got it.
just one thing, we need to add a profile picture for a user to display in the pages "following" and "people"
different cases:
- you registered with facebook: We use your facebook profile picture.
- you register in the normal way: in the way twitter do it, we will assign a default profile pic for users and add in the settings page the possibility to change and upload a new one.

we also need a search box (on top or only on the everyone page? what do you prefer?) to look for people, the "everyone" page won't be enough. with this search box, would you want to have autosuggestions? (I mean, as fb does it, when you start typing in the box, people matching appears underneath). this is nice but a bit longer to implement.

when you are viewing a person's journal, here is what will change from viewing your journal:
- no edit photo icon
- instead of the "upload photo" button, a "follow" button
- add the profile and username of the person

on the "everyone" and "following" page, how do we handle lot of people, for now, we could leave it and display all in the page but sooner or later we will have to implement either a pagination system or a infinite scrolling (when you go at the bottom of the page, it loads more people). do you want to leave that for now or do you want to implement it directly?
I would suggest you to leave it for now, it will be a better user experience when we start having users.

That's all technical point I wanted to share, just to let you know all the development work that it involves.
can you respond to the few questions? are you ok with that? anything else to add?

**Comment by jdaudier** [comment]
Can we use this as the default profile pic when user doesn't have a photo (this is for placement for now)?
http://sportsvite.com/images/user/50_dummyuser_nonmember.gif

Search box: Maybe we can add it to a future sprint.  For now, since we don't have many users, maybe we can just dump everyone into the "Everyone" page and add infinite scrolling?

**Comment by loicginoux** [comment]
I am working on that.
in the people list, do you not want to have the username displayed? if yes were should we put it? when hovering over the picture or below? 
I like this way of displaying:
http://geekli.st/search?

**Comment by loicginoux** [comment]
also:
- do you want to have yourself on the "all people" page? I suggest better without yourself
- do you want to have the people you already follow on the "all people" page? I suggest better not to display them.

Let me know if it's fine or if you think differently.

**Comment by jdaudier** [comment]
Agreed - without yourself in "Everyone" page
Agreed - people on your "Following" page won't show up on "Everyone" page

**Comment by jdaudier** [comment]
I like the geekli.st way of showing users

**Comment by jdaudier** [comment]
Can we use this as the default profile pic when user doesn't have a photo?  I got permission to use this.
http://sportsvite.com/images/user/50_dummyuser_nonmember.gif

**Comment by jdaudier** [comment]
For the "Challenger" page, is it hard to add all the user you currently follow at the bottom?  Now that I think about it, it might be nice to see everyone - the only difference is they'll say "UNFOLLOW" next to their name.

**Comment by loicginoux** [comment]
no it's fine, I'll do that on sprint 4

**Comment by jdaudier** [comment]
Another question, is it possible to see your entries right after you log in?  Meaning, we can remove the "HOME" link (clicking the logo can bring your to your diary page if you're on other pages).

**Comment by loicginoux** [comment]
my opinion: I would keep the HOME link but rename it "Dashboard". why would I keep a clear link to this page? because people might look after the link to go their "dashboard" page. 
I was thinking about the logo link to go to the homepage of the marketing site...

but you are the boss and you have the last word :)

**Comment by jdaudier** [comment]
How about changing "home" to "MY DIARY"?  Is there a way to go straight to the DIARY page after they log in though (one less click)?

**Comment by loicginoux** [comment]
:/
not sure to understand, you already go straight to your diary when logging in, no? 
I just logged in and went straight to http://www.foodrubix.com/<MY_USERNAME>

**Comment by jdaudier** [comment]
After I've logged in, I go in on another day by typing www.foodrubix.com, I am taken to this page, not my diary page: http://screencast.com/t/gGnrcwns

**Comment by loicginoux** [comment]
ah I see, so you mean that if a user is logged in the root of the site www.foodrubix.com should redirect to www.foodrubix.com/<MY_USERNAME> ?
what I will do is if there is a user logged in the root goes to the diary page, if not, it goes to the presentation site (foodrubix.com/welcome for example)

**Comment by jdaudier** [comment]
right
