### ISSUE TITLE
should we make photos optional when uploading? 

### ISSUE THREAD

**Issue by loicginoux** [loicginoux/joanne_project#321]
As the video tester shows us, people seems to not be able to upload a picture of EVERYTHING they eat, So to facilitate things, should we allow people to "upload" and just put the calories? We would then put a default picture.

**Comment by jdaudier** [comment]
Maybe when a user does not upload a photo, is it possible to to ask them:
Would you like to use a default image? 
[SALAD] [MEAT DISH] [DESSERT] [NUT BAR] - buttons?

Should we come up with a handful of default photos?

**Comment by loicginoux** [comment]
We could do yes, but that would involve a bit more work. 
What would be the advantage of doing this? It doesn't bring much more, no?

**Comment by jdaudier** [comment]
let's hold off on this till later on when we have more time

**Comment by loicginoux** [comment]
ok

**Comment by jdaudier** [comment]
The more I think about this, the more I think it's not a good idea since the whole purpose of the site is to take photos and become more aware of what you're eating.  The only thing would be if we let them put in text and that converts to photos like what Shereen has done: http://s3.amazonaws.com/foodrubix-production/photos/4293/big.jpg?1363215151

**Comment by loicginoux** [comment]
I close this for now then
