### ISSUE TITLE
Upload progress bar bug

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#326]
Check out this beta tester's video:  https://betapunch.viewscreencasts.com/29f5cae598cb40d5992d1af06f564aba

A few things:

1) Does the top nav icons look stretched to you?

2) There's something wrong with the upload preview. There's a ? and after she uploads, it doesn't show a preview.
![2013-04-13_2059](https://f.cloud.github.com/assets/1666031/377463/793a5e4c-a4b9-11e2-822d-e9ab41360908.png)

3) She completes misses the Settings menu. I think we should make the down arrow larger, orange and more noticeable.  And add in some text in parenthesis and bold it.  Thoughts?

![arrow](https://f.cloud.github.com/assets/1666031/377466/405e0938-a4ba-11e2-8ea2-ede23ea395fb.png)

**Comment by loicginoux** [comment]
1) It looked stretched on her screen yes. I can't reproduce it in any of my browsers.
2)  I think this is due to her browser. It seems like it is Safari but my test in Safari is working. Maybe she has an older version...
3) I could make a link on "Settings menu" in the box. I don't think making it larger and orange will help really. It will just look bad.

Other Thoughts about this video:
4) I will make the calories input in the form without the two small arrows on the right of it. It doesn't bring anything and confuse people.
5) I agree with her saying that the user survey popup is annoying when first logging in. It's too intrusive.
6) We need a guide with the different steps when first logging in to drive people through the app. (I think we already have an issue created for that)

**Comment by jdaudier** [comment]
2) I thought it they use an older browser, we had a pop-up that'll tell them to upgrade?
3) So you don't think we should make the down arrow more noticeable?
5) I am trying to find out if I can time the survey popup to show up later.

**Comment by jdaudier** [comment]
2) She has Safari Version 5.1.7(7534.57.4)

**Comment by loicginoux** [comment]
1) Icons look stretched in Safari 5.1.7, I will fix that.
2) We did implement the script for older browser but her one is not that old, we display messages for Safari under v5. For browsers that can't display the image before uploading, I am just displaying the path of the file.
3) I don't think it's a good idea, no. this is how it will look like: http://awesomescreenshot.com/0e415wx8fd with settings as link and a close button.

**Comment by jdaudier** [comment]
2) So her version of Safari won't display the images before uploading?

3) How about making the text easier to read by using bullets?
![2013-04-15_0744](https://f.cloud.github.com/assets/1666031/381235/588f9b1c-a5db-11e2-89ff-6fd73f8acfb5.png)

**Comment by loicginoux** [comment]
2) no she will see instead on the box the path to the file she uploaded.
3) agreed, I will make it a list

**Comment by jdaudier** [comment]
2) So that's because her browser version doesn't support preview?

**Comment by loicginoux** [comment]
2) yes more exactely, we are talking about the File API which allows preview of images.
