### ISSUE TITLE
Compare last week's calorie feature in the chart

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#335]
Would it be hard to have a "COMPARE" button in the weekly view (on the site) that lets you pull up last week's data and compare that against this week's similar to Google Analytics?

When you press the COMPARE button, it will draw 2 lines to compare this week with previous week. Like Google Analytics. I think we can do this just for the weekly view first.

![GA](https://f.cloud.github.com/assets/1666031/435104/3144a412-af9f-11e2-95da-69d89596d093.png)

**Comment by jdaudier** [comment]
Is it hard to add the compare feature to month view so you can compare last month to this month?

**Comment by loicginoux** [comment]
I will see if the graphic library allows me to compare easily if there is
not exactly the same amount of data ( 30 days compared to 31)

**Comment by loicginoux** [comment]
where do you think the button should go? 
http://awesomescreenshot.com/01718m7g96

**Comment by jdaudier** [comment]
I like it here. You?
![2013-05-05_1348](https://f.cloud.github.com/assets/1666031/464162/634fed6e-b5c5-11e2-9e8f-078457c24c48.png)

**Comment by loicginoux** [comment]
Agreed

**Comment by loicginoux** [comment]
This is the current graphic for the month view 
http://awesomescreenshot.com/0d7190xe0d

and the graphic when comparing 2 months:
http://awesomescreenshot.com/038190wj59

As you can see on the graphic on the X-axis, each point correspond to a particular date and not a day number 
 The problem is that when comparing 2 months, the lines don't superpose.
2 solutions:
- we keep the X-axis like it is. Comparison lines will not superpose.
- for each points, on the X-axis we will only be showing a number between 1 and 31. The X-axis will not show the month anymore, only the day number, but when comparing, the two lines will superpose.

Is the solution 2 ok with you?

**Comment by jdaudier** [comment]
I think the lines have to superpose like Google Analytics for it to be useful.

How would this look like?
for each points, on the X-axis we will only be showing a number between 1 and 31. The X-axis will not show the month anymore, only the day number, but when comparing, the two lines will superpose.

**Comment by jdaudier** [comment]
Can we make the COMPARE button orange so it stands out?

**Comment by loicginoux** [comment]
Ok,
As I was on the graphic I changed his look a bit. here is the comparison for the week view:
http://awesomescreenshot.com/05e192bd06
I will push the current state on staging site at the end of the day.

**Comment by jdaudier** [comment]
That looks great!  Can we add a bit of white margin below the compare button so it's not touching the chart?

**Comment by loicginoux** [comment]
This is deployed on testing site as well as last weekly and daily emails.

**Comment by loicginoux** [comment]
compare button is now with a toggle state in staging site.

**Comment by jdaudier** [comment]
Can we change the text on the button to say:
Compare to Last Week
Remove Comparison

**Comment by loicginoux** [comment]
ok

**Comment by jdaudier** [comment]
Updated: Compare to Last Week

**Comment by loicginoux** [comment]
changed in testing
