### ISSUE TITLE
Default view changed

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#354]
I think the default view changed from weekly to monthly for some reason. Can we change it back?

**Comment by loicginoux** [comment]
should be fine now.

**Comment by jdaudier** [comment]
any idea why this changed?

**Comment by loicginoux** [comment]
It was a weird cookie problem. I store a cookie that says "period='week'" or "month" or "day". This allow the page to know which view to open first. This cookie is overwritten every time you click a period button. This cookie is normally recorder only once and you cannot have the same cookie twice. The problem is that for a reason I still not understand this cookie was set twice and when reading it, it always retrieving the "month" period.
What I did is removing this cookie functionality so that it always load the week view first. If you still want this functionality, let me know and I will need to spend a bit more time to understand more why this bug was happening.

**Comment by jdaudier** [comment]
I guess that's ok since most people probably use the "week" view.
