### ISSUE TITLE
Date drop down menu bug

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#49]
When I upload a photo, enter the calories, then try to change the date, the drop-down menu doesn't show up.  I think it might work the first time I do this but not any time after that.

**Comment by loicginoux** [comment]
do you mean it work when you upload but not when you edit? the two box for uploading and editing are similar but the code behind is different. that's why I am asking.
I can't replicate neither on Firefox or chrome. 
Could we do a skype call and by sharing your screen you will show me that? Give me a shout when you are available and I am online.

**Comment by jdaudier** [comment]
You can see it here: https://dl.dropbox.com/u/125982/Date-bug.mp4

For the 2nd photo, notice how the date drop down menu doesn't show up and the date auto changed to 9/3?

**Comment by loicginoux** [comment]
great video!!! much easier to understand, I didn;t understand what you meant and I didn't try that.... 
Ok so I actually have the same issue. thanks I can now start debugging it :)

**Comment by loicginoux** [comment]
ok this should be fixed, can you test and close this issue if it's working for you?

**Comment by jdaudier** [comment]
works now - thanks
