### ISSUE TITLE
Pop-up menu missing

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#50]
In the past, when you hover over a thumbnail, there's a popup showing you the calories and time.  Can we add that back?

**Comment by loicginoux** [comment]
Can we discuss it first? :) 
The reason why I removed it is that I thought it was too much to have the same information (calories and upload date) when hovering and also when clicking the image. because I started implementing the box for comments, likes and information, I thought the other one was unnecessary and was making the interface too heavy.
your thought?

**Comment by jdaudier** [comment]
I noticed that the calories and date popup was helpful when I had to edit or rearrange the photos.  I can easily change the order of a photo based on what I see in a popup.  But I guess it might be less useful once we make the images drag and drop.  So if we plan on doing the drag and drop feature, we probably don't need the popup as reference.

**Comment by loicginoux** [comment]
what about putting a small badge for calories and time on the overlay (like comments and likes)? in the same way as http://www.sweeterspoon.com/

**Comment by jdaudier** [comment]
Sounds good

**Comment by loicginoux** [comment]
this is now deployed on heroku, are you ok with it?

**Comment by jdaudier** [comment]
Looks good
