### ISSUE TITLE
Email replies to real person

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#90]
Can we make daily / weekly emails reply-able?  You can use hi@foodrubix.com as the reply email.

**Comment by loicginoux** [comment]
Ok so all emails sent by the app will be sent from hi@foodrubix.com so they will be able to respond to it

**Comment by jdaudier** [comment]
so I can test this from tonight's email?

**Comment by loicginoux** [comment]
yes all emails are sent from the email above

**Comment by jdaudier** [comment]
Can we change it so it shows up as FoodRubix on the email FROM line instead of hi@foodrubix.com?

**Comment by loicginoux** [comment]
I am not sure we can change that. Before it was already showing as "foodrubix@foodrubix.mailgun.org". Maybe this can be done on mailgun but I don't think so. Also there is already a [Foodrubix] at the beginning of every email subject that foodrubix send. I think this is clear enough.

**Comment by jdaudier** [comment]
sounds good

**Comment by loicginoux** [comment]
Also if you are using foodrubix@foodrubix.com instead of hi@foodrubix.com, the from will appear as "foodrubix" instead of appearing as "hi" like this does for me at the moment:. you can see two emails in the screenshot with the two different email address. the first one is sent from  hi@foodrubix.com and the second from the old  foodrubix@foodrubix.mailgun.org
http://awesomescreenshot.com/0b2ngi46b

**Comment by jdaudier** [comment]
Are we using Mailgun to send the email?  Usually in email systems, they'll let you enter your email and the name you want to show up when you send an email in the FROM field.  I wonder if there's something similar.
